### ISSUE TITLE
Cross-collaboration with other repos

### ISSUE THREAD

**Issue by DonaldTsang** [umcconnell/lc4#1]
- Python https://github.com/dstein64/LC4
- JS https://github.com/Gavin-Song/elsie-four-cipher
- Go https://github.com/tonetheman/golang_lc4

**Comment by umcconnell** [comment]
Sounds like a great idea, @DonaldTsang !  :+1:

How exactly do you imagine this?
(e.g. implementing same features, same api, etc...)

**Comment by DonaldTsang** [comment]
1. A better ReadMe noting other repos
2. Coordination of features
3. A proper specification document

**Comment by umcconnell** [comment]
Thanks for the ideas :+1: 

I'll work on that!

**Comment by umcconnell** [comment]
Added links in README: 6348606e3295154ccf4cf39b4fc72563b215f859
