### ISSUE TITLE
Minified version

### ISSUE THREAD

**Issue by DonaldTsang** [umcconnell/lc4#3]
I would be great to see a minified version of LC4 (whole implementation) for portability?
it should be a browser terminal based tool that has

 - [ ] Key exapnsion like in https://gitea.blesmrt.net/exa/ls47 could be in future versions.

**Comment by umcconnell** [comment]
For the browser part, you can use a minified version through jsdelivr:

```html
<script type="module">
    import {
        encrypt,
        generateKey
    } from "https://cdn.jsdelivr.net/gh/umcconnell/lc4@1/src/main.min.js";

    // Your code...
</script>
```

**Comment by umcconnell** [comment]
Added minification to node version (see: #6 ).

**Comment by umcconnell** [comment]
I'd like to keep the API the way it is, as you can specify nonce, header, signature if you want with the options object. I don't think two modes with different minified formats and arguments are needed.

However, I will work on a minified version of the whole library for the browser as soon as I have time.
I'll also look into the key expansion.
